version: "3"

tasks:
  
  check:
    cmds:
      - task: build-flags
      - mise x -- clang-format -i src/*.[ch]
      - mise x -- clang-tidy src/*.[ch]
    sources:
      - src/*
        
  build:
    desc: Build StayAwake
    deps: [ check ]
    cmd: mise x -- zig build
    sources:
      - src/*
    generates:
      - ./zig-out/bin/StayAwake-windows-x86_64.exe
      
  run:
    desc: Run StayAwake
    deps: [ build ]
    cmd: cmd /c start "" "./zig-out/bin/StayAwake-windows-x86_64.exe"
    
  build-flags:
    cmd: mise x -- zig build compile-flags

  release:
    desc: "Create new release and publish on GitHub (Usage: task release VERSION=1.2.0)"
    summary: |
      Prepares the release by updating version headers, builds the binary, and publishes it to GitHub.
      Requirements: Bun, Zig, and GitHub CLI (gh) must be installed.
    cmds:
      # 1. Update version strings
      - mise x -- bun ./scripts/prepare-release.ts {{.VERSION}}
      
      # 2. Automated Git Workflow
      - git add src/app_state.h resource.rc
      - 'git commit -m "chore: prepare release v{{.VERSION}}"'
      - git push
      - echo "✅ Changes committed and pushed to origin."
      
      # 3. Build and publish
      - mise x -- zig build
      - |
        mise x -- gh release create "v{{.VERSION}}" \
          ./zig-out/bin/StayAwake-windows-x86_64.exe \
          --title "v{{.VERSION}}: $(cat release_title.txt)" \
          --notes-file release_notes.md      
      - rm release_title.txt release_notes.md
      - echo "🚀 Release v{{.VERSION}} successfully published!"
    preconditions:
      - sh: 'test -n "{{.VERSION}}"'
        msg: "Error: VERSION variable is missing. Example: task release VERSION=1.2.0"
      - sh: "mise x -- gh auth status"
        msg: "Error: You must be logged into the GitHub CLI (gh auth login)."
      - sh: "test -f release_title.txt"
        msg: "Error: 'release_title.txt' missing."
      - sh: "test -f release_notes.md"
        msg: "Error: 'release_notes.md' missing."
      - sh: "git diff --exit-code"
        msg: "Error: You have uncommitted changes. Please stash or commit them first."